### ISSUE TITLE
Only a Question

### ISSUE THREAD

**Issue by Ganktimebaby** [MatthewDwyer/botman#5]
Is it possible that Botman writes as a own user?
Without Server:  

Think we have only the /say command atm or?

I searchd at servertools coppis and badcompany for an Option:/

Thanks

**Comment by MatthewDwyer** [comment]
Sorry that is not possible at least from the bot.  That would require a server-side mod and I'm not aware of any that currently do that.  Several do change player names in various ways but the server is not a player.  Since the bot is not a player either, everything it says comes from Server.

**Comment by Ganktimebaby** [comment]
Codet one for scriptingmod works now without server: before the text
